# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT
# 缩小固件体积 → 让两个宏都能放下
CONFIG_ZMK_KEYCODE_DICT_COMPRESSION=y
CONFIG_ZMK_KEYCODE_DICT_MINIMIZE=y
CONFIG_ZMK_IDLE_REPORTS=n
CONFIG_ZMK_DISPLAY=n