# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_SOLID=y      # 静态
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_BREATHE=y     # 呼吸
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_SPECTRUM=y    # 彩虹循环
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_SWIRL=y       # 漩涡
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_TRAIL=y       # 轨迹/跑马
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_GRADIENT=y    # 渐变
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_RANDOM=y      # 随机