# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT
# 基础必须开启
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PINCTRL=y

# RGB 核心开启（必须全加）
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EFFECTS=y
CONFIG_ZMK_RGB_UNDERGLOW_ADAFRUIT_LED_EFFECTS=y
CONFIG_WS2812_STRIP=y

# 动画必须开启
CONFIG_ZMK_RGB_UNDERGLOW_BREATHE=y
CONFIG_ZMK_RGB_UNDERGLOW_SPECTRUM=y
CONFIG_ZMK_RGB_UNDERGLOW_SWIRL=y
CONFIG_ZMK_RGB_UNDERGLOW_CYCLE=y