# Copyright (c) 2022-2023 XiNGRZ
# SPDX-License-Identifier: MIT
# 基础
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_PINCTRL=y
CONFIG_USB=y
CONFIG_USB_DEVICE_STACK=y

# RGB 核心
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EFFECTS=y
CONFIG_WS2812_STRIP=y

# 默认全黑
CONFIG_ZMK_RGB_UNDERGLOW_DEFAULT_EFFECT=-1

# 关闭背景动画
CONFIG_ZMK_RGB_UNDERGLOW_BREATHE=n
CONFIG_ZMK_RGB_UNDERGLOW_SPECTRUM=n
CONFIG_ZMK_RGB_UNDERGLOW_SWIRL=n
CONFIG_ZMK_RGB_UNDERGLOW_CYCLE=n

# 踏雪留痕 + 彩虹色
CONFIG_ZMK_RGB_UNDERGLOW_KEY_TRAIL=y
CONFIG_ZMK_RGB_UNDERGLOW_KEY_TRAIL_DECAY=85
CONFIG_ZMK_RGB_UNDERGLOW_KEY_TRAIL_BRIGHTNESS=130
CONFIG_ZMK_RGB_UNDERGLOW_KEY_TRAIL_COLOR=-1