manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # 👈 改成 main 或 v0.12.0
      import: app/west.yml
  self:
    path: config