name: ZMK Build NO PIP NO APT
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: "hw75_keyboard@1.1"
          - board: "hw75_dynamic@1.1"

    steps:
      - uses: actions/checkout@v4

      - name: West init
        run: |
          west init -l config
          west update --narrow -o=--depth=1
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: zmk-${{ matrix.board }}
          path: build/zephyr/zmk.uf2
